# Generated by Django 5.2.16 on 2026-08-28 20:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_scan_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_scan_finished_at', models.DateTimeField(blank=True, null=True)),
                ('files_seen', models.PositiveIntegerField(default=0)),
                ('files_added', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedup_key', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=16)),
                ('priority', models.IntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'scheduled_for', '-priority'], name='job_claim_idx'), models.Index(fields=['state', 'lease_expires_at'], name='job_lease_idx'), models.Index(fields=['-created_at'], name='job_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ['QUEUED', 'RUNNING']), models.Q(('dedup_key', ''), _negated=True)), fields=('dedup_key',), name='job_unique_active_dedup_key')],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('previous_path', models.CharField(blank=True, max_length=1024)),
                ('planned_path', models.CharField(blank=True, max_length=1024)),
                ('plan_note', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mtime', models.FloatField(default=0.0)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('bitrate', models.PositiveIntegerField(default=0)),
                ('fingerprint', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('artist', models.CharField(blank=True, max_length=512)),
                ('album', models.CharField(blank=True, max_length=512)),
                ('album_artist', models.CharField(blank=True, max_length=512)),
                ('track_no', models.PositiveIntegerField(default=0)),
                ('disc_no', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField(default=0)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('is_compilation', models.BooleanField(default=False)),
                ('musicbrainz_recording_id', models.CharField(blank=True, max_length=64)),
                ('musicbrainz_release_id', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(choices=[('LIBRARY', 'Existing library'), ('YOUTUBE', 'YouTube')], db_index=True, default='LIBRARY', max_length=16)),
                ('identified_by', models.CharField(blank=True, max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('state', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('IDENTIFYING', 'Identifying'), ('IDENTIFIED', 'Identified'), ('ORGANIZED', 'Organized'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('MISSING', 'File missing')], default='DISCOVERED', max_length=16)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('organized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['state', 'retry_at'], name='track_state_retry_idx'), models.Index(fields=['state', 'source'], name='track_state_source_idx'), models.Index(fields=['album_artist', 'album'], name='track_album_idx'), models.Index(fields=['-created_at'], name='track_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('video_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('uploader', models.CharField(blank=True, max_length=255)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True, max_length=1024)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('PRIVATE', 'Private'), ('UNAVAILABLE', 'Unavailable'), ('DELETED', 'Deleted')], db_index=True, default='AVAILABLE', max_length=16)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_video', to='music.track')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['availability', 'retry_at'], name='yt_avail_retry_idx')],
            },
        ),
    ]
