# Generated by Django 5.2.16 on 2026-08-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_embedded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='cover_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
